#!/bin/sh
#
# Set up environment variables for general build tool to operate
#
export ZOPEN_TYPE="TARBALL"

export ZOPEN_TARBALL_URL="https://gnu.askapache.com/diffutils/diffutils-3.8.tar.xz"
export ZOPEN_TARBALL_DEPS="curl xz make"

export ZOPEN_BOOTSTRAP=skip

zopen_check_results()
{
  return 3 # non-functional
}

zopen_check_results()
{
chk="$2_check.log"

failures=$(egrep '^# FAIL:|^# ERROR:|^# XFAIL' ${chk} | tail -1 | awk ' { print $3; }')
totalTests=$(egrep '^# ERROR:|^# PASS:|^# XFAIL:|^# FAIL:|^# XPASS:' ${chk} | tail -1 | awk ' { print $3; }')

cat <<ZZ
actualFailures:$failures
totalTests:$totalTests
expectedFailures:0
ZZ
}
