#!/bin/sh
#
# Set up environment variables for general build tool to operate
#
export ZOPEN_TYPE="TARBALL"

export ZOPEN_TARBALL_URL="https://gnu.askapache.com/diffutils/diffutils-3.8.tar.xz"
export ZOPEN_TARBALL_DEPS="curl xz make"

export ZOPEN_BOOTSTRAP=skip

zopen_check_results()
{
  return 3 # non-functional
}

zopen_check_results()
{
#!/bin/sh
#
# Results should be 0 errors, and no more than 10 failures
# FAIL:	 10
# ERROR: 0
#
set -x
chk="$2_check.log"

failures=$(egrep '^# FAIL:' ${chk} | tail -1 | awk ' { print $3; }')
if [ ${failures} -gt 10 ]; then
  exit 2
fi
errors=$(egrep '^# ERROR:' ${chk} | tail -1 | awk ' { print $3; }')
if [ ${errors} -gt 0 ]; then
  exit 2
fi

exit 1
}
