#!/bin/sh
#
# Set up environment variables for general build tool to operate
#
export ZOPEN_TYPE="TARBALL"

export ZOPEN_TARBALL_URL="https://gnu.askapache.com/diffutils/diffutils-3.8.tar.xz"
export ZOPEN_TARBALL_DEPS="curl xz make zoslib"

export ZOPEN_EXTRA_CFLAGS="-Wno-unused-const-variable -Wno-tautological-constant-out-of-range-compare -Wno-missing-prototypes -Wno-tautological-compare -Wno-implicit-function-declaration"
export ZOPEN_BOOTSTRAP=skip

zopen_check_results()
{
chk="$2_check.log"

ERROR=$(egrep '^# ERROR:' ${chk} | tail -1 | awk '{ print $3; }')
SKIP=$(egrep '^# SKIP:' ${chk} | tail -1 | awk '{ print $3; }')
PASS=$(egrep '^# PASS:' ${chk} | tail -1 | awk '{ print $3; }')
FAIL=$(egrep '^# FAIL:' ${chk} | tail -1 | awk '{ print $3; }')
XFAIL=$(egrep '^# XFAIL:' ${chk} | tail -1 | awk '{ print $3; }')
TOTAL=$(egrep '^# TOTAL:' ${chk} | tail -1 | awk '{ print $3; }')

totalTests=$(echo "${TOTAL}-${SKIP}" | bc )
actualFailures=$(echo "${FAIL}+${XFAIL}+${ERROR}" | bc)

cat <<ZZ
actualFailures:$actualFailures
totalTests:$totalTests
expectedFailures:12
ZZ
}
